#!/bin/sh
#
# vyatta-uqda - A uqda package for Ubiquiti EdgeOS, VyOS and other
# Vyatta-based systems.
# Copyright (C) 2018 Neil Alexander T.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ ! -z $1 ];
then
    echo "Restarting uqda interface $1..."
    sudo systemctl restart uqda@$1
else
    if [ `ls /config/uqda.*.conf 2>/dev/null | wc -l` -gt 0 ];
    then
        ls /config/uqda.*.conf | awk -v FS="(uqda.|.conf)" '{print $3}' | while read file;
        do
            echo "Restarting uqda interface $file..."
            sudo systemctl restart uqda@$file
        done
    fi
fi
