#!/bin/sh
#
# Put the uqda and uqdactl binaries into /usr/local/bin
# Then copy this script into /usr/local/etc/rc.d/uqda
# Finally, run:
#   1. chmod +x /usr/local/etc/rc.d/uqda /usr/local/bin/{uqda,uqdactl}
#   2. echo "uqda_enable=yes" >> /etc/rc.conf
#   3. service uqda start
#
# PROVIDE: uqda
# REQUIRE: networking
# KEYWORD:

. /etc/rc.subr

name="uqda"
rcvar="uqda_enable"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

CONFFILE="/usr/local/etc/uqda/uqda.conf"
pidfile="/var/run/uqda/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f"

uqda_start()
{
	if [ ! -x /usr/local/bin/uqda ]; then
		logger -s -t uqda "Warning: /usr/local/bin/uqda is missing or not executable"
		logger -s -t uqda "Copy the uqda binary into /usr/local/bin and then chmod +x /usr/local/bin/uqda"
		return 1
	fi

	if [ ! -f "$CONFFILE" ]; then
		logger -s -t uqda "Missing $CONFFILE; create or migrate persistent identity before starting"
		return 1
	fi
	/usr/local/bin/uqda -useconffile "$CONFFILE" -checkconf || return 1

	test ! -d /var/run/uqda && mkdir -p /var/run/uqda

	logger -s -t uqda "Starting uqda"
	${command} ${command_args} /usr/local/bin/uqda -useconffile "${CONFFILE}" \
		1>/var/log/uqda.stdout.log \
		2>/var/log/uqda.stderr.log &
}

uqda_stop()
{
	logger -s -t uqda "Stopping uqda"
	test -f /var/run/uqda/${name}.pid && kill -TERM $(cat /var/run/uqda/${name}.pid)

}

load_rc_config $name
: ${uqda_enable:=no}

run_rc_command "$1"
