# syntax=docker/dockerfile:1
FROM --platform=$BUILDPLATFORM docker.io/golang:alpine AS builder

COPY . /src
WORKDIR /src

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
ARG UQDA_VERSION
ENV CGO_ENABLED=0
ENV GOOS=${TARGETOS} GOARCH=${TARGETARCH}

RUN set -eux; \
    apk add --no-cache git; \
    if [ "$TARGETARCH" = arm ] && [ -n "$TARGETVARIANT" ]; then \
      export GOARM="${TARGETVARIANT#v}"; \
    fi; \
    UQDA_VERSION="${UQDA_VERSION:-}" ./build; \
    go build -o /src/genkeys cmd/genkeys/main.go

FROM docker.io/alpine

COPY --from=builder /src/uqda /usr/bin/uqda
COPY --from=builder /src/uqdactl /usr/bin/uqdactl
COPY --from=builder /src/genkeys /usr/bin/genkeys
COPY contrib/docker/entrypoint.sh /usr/bin/entrypoint.sh

# RUN addgroup -g 1000 -S uqda \
#  && adduser -u 1000 -S -g 1000 --home /etc/uqda uqda
#
# USER uqda
# TODO: Make running unprivileged work

VOLUME [ "/etc/uqda" ]

ENTRYPOINT [ "/usr/bin/entrypoint.sh" ]
