#!/bin/sh

CONFFILE="/etc/uqda/uqda.conf"

probetun() {
	modprobe tun
	return $?
}

start() {
	if [ ! -f "$CONFFILE" ]; then
		echo "Missing $CONFFILE; create or migrate your persistent identity before starting Uqda" >&2
		return 1
	fi
	/usr/bin/uqda -useconffile "$CONFFILE" -checkconf || return 1

	if [ ! -e /dev/net/tun ]; then
		printf 'Inserting TUN module: '
		if probetun; then
			echo "OK"
		else
			echo "FAIL"
			return 1
		fi
	fi

	printf 'Starting uqda: '
	if start-stop-daemon -S -q -b -x /usr/bin/uqda \
		-- -useconffile "$CONFFILE"; then
		echo "OK"
	else
		echo "FAIL"
	fi
}

stop() {
	printf "Stopping uqda: "
	if start-stop-daemon -K -q -x /usr/bin/uqda; then
		echo "OK"
	else
		echo "FAIL"
	fi
}

reload() {
	printf "Reloading uqda: "
	if start-stop-daemon -K -q -s HUP -x /usr/bin/uqda; then
		echo "OK"
	else
		echo "FAIL"
		start
	fi
}

restart() {
	stop
	start
}

case "$1" in
	start|stop|restart|reload)
		"$1";;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac

exit 0
