#!/bin/sh
#
# vyatta-uqda - A uqda package for Ubiquiti EdgeOS, VyOS and other
# Vyatta-based systems.
# Copyright (C) 2018 Neil Alexander T.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -eu

IFNAME=${1:-}
if ! printf '%s\n' "$IFNAME" | grep -Eq '^tun[0-9]+$'; then
	echo "usage: $0 tunN" >&2
	exit 2
fi

CONFIG="/config/uqda.$IFNAME.conf"
if [ -f "$CONFIG" ]; then
	echo "UQDA configuration $CONFIG already exists; leaving it unchanged"
else
	echo "Generating UQDA configuration for $IFNAME"
	umask 077
	TMP="${CONFIG}.tmp.$$"
	trap 'rm -f "$TMP"' EXIT HUP INT TERM
	/usr/local/bin/uqda -genconf > "$TMP"
	sed -i \
		-e "s|IfName: auto|IfName: $IFNAME|" \
		-e "s|AdminListen: unix:///var/run/uqda.sock|AdminListen: unix:///run/uqda-$IFNAME.sock|" \
		"$TMP"
	mv "$TMP" "$CONFIG"
	trap - EXIT HUP INT TERM
fi
